version: "3.6"
services:
  reverse-proxy:
    networks:
      default:
        aliases:
          - 'cdn-mapstorage.workadventure.localhost'

  minio-mapstorage:
    image: bitnami/minio:2022.9.7
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-mapstorage.rule=Host(`minio-mapstorage.workadventure.localhost`)"
      - "traefik.http.routers.minio-mapstorage.entryPoints=web"
      - "traefik.http.services.minio-mapstorage.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio-mapstorage.service=minio-mapstorage"
      - "traefik.http.routers.cdn-mapstorage.rule=Host(`cdn-mapstorage.workadventure.localhost`)"
      - "traefik.http.routers.cdn-mapstorage.entryPoints=web"
      - "traefik.http.services.cdn-mapstorage.loadbalancer.server.port=9000"
      - "traefik.http.routers.cdn-mapstorage.service=cdn-mapstorage"
    environment:
      MINIO_ROOT_USER: "minio-access-key"
      MINIO_ROOT_PASSWORD: "minio-secret-access-key"
      MINIO_DEFAULT_BUCKETS: "mapstorage:public"
      MINIO_SITE_REGION: "eu-west-1"
    volumes:
      - minio-mapstorage:/data

  map-storage:
    environment:
      AWS_ACCESS_KEY_ID: "minio-access-key"
      AWS_SECRET_ACCESS_KEY: "minio-secret-access-key"
      AWS_DEFAULT_REGION: "eu-west-1"
      AWS_BUCKET: "mapstorage"
      AWS_URL: "http://minio-mapstorage:9000"
      AWS_ENDPOINT: "http://cdn-mapstorage.workadventure.localhost/"
      USE_DOMAIN_NAME_IN_PATH: "true"

volumes:
  minio-mapstorage:
