---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "workadventure.fullname" . }}-env-chat
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
data:
  PUSHER_URL: {{ include "workadventure.pusherUrl" . | quote }}
  UPLOADER_URL: {{ include "workadventure.uploaderUrl" . | quote }}
  EJABBERD_WS_URI: {{ printf "%s/xmpp/ws" (include "workadventure.ejabberdWsUrl" .) }}/xmpp/ws
  EJABBERD_DOMAIN: {{ .Values.ejabberdDomain | quote }}

  {{- range $key, $val := .Values.commonEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{- range $key, $val := .Values.chat.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
