{{- if and .Values.ingress.enabled .Values.singleDomain -}}
{{- $fullName := include "workadventure.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-path
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotationsPath }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.domainName }}
      secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /api{{ .Values.ingress.rewritePathSuffix }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-back
                port:
                  number: {{ .Values.back.service.port }}
          - path: /uploader{{ .Values.ingress.rewritePathSuffix }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-uploader
                port:
                  number: {{ .Values.uploader.service.port }}
          - path: /icon{{ .Values.ingress.rewritePathSuffix }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-icon
                port:
                  number: {{ .Values.icon.service.port }}
          - path: /map-storage{{ .Values.ingress.rewritePathSuffix }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-mapstorage
                port:
                  number: {{ .Values.mapstorage.service.port }}
          - path: /room-api
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-room-api
                port:
                  number: {{ .Values.play.roomApiService.port }}
          {{- if and .Values.excalidraw.enabled .Values.excalidraw.ingress -}}
          - path: /excalidraw-storage{{ .Values.ingress.rewritePathSuffix }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-excalidraw-storage
                port:
                  number: {{ .Values.excalidraw.excalidrawStorage.service.port }}
          - path: /excalidraw-room{{ .Values.ingress.rewritePathSuffix }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-excalidraw-room
                port:
                  number: {{ .Values.excalidraw.excalidrawRoom.service.port }}
          - path: /excalidraw{{ .Values.ingress.rewritePathSuffix }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-excalidraw
                port:
                  number: {{ .Values.excalidraw.excalidraw.service.port }}
          {{- end }}
{{- end }}
