{{- if and (or .Values.ingress.enabled .Values.play.ingress.enabled) (not .Values.singleDomain) -}}
{{- $fullName := include "workadventure.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-play
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotationsRoot }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $ingressClassName := coalesce .Values.play.ingress.className .Values.ingress.className -}}
  {{- if $ingressClassName }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  {{- $tls := coalesce .Values.play.ingress.tls .Values.ingress.tls false -}}
  {{- if $tls }}
  tls:
    - hosts:
        - {{ (include "workadventure.playDomainName" .) | quote }}
        - {{ (include "workadventure.pusherDomainName" .) | quote }}
      secretName: {{ .Values.play.ingress.secretName | default (printf "%s-play-cert" (include "workadventure.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ (include "workadventure.playDomainName" .) | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-play
                port:
                  number: {{ .Values.play.service.port }}
    - host: {{ (include "workadventure.pusherDomainName" .) | quote }}
      http:
        paths:
          - path: /ws/
            pathType: Prefix
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-play
                port:
                  number: {{ .Values.play.service.wsPort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-play
                port:
                  number: {{ .Values.play.service.port }}
    - host: {{ (include "workadventure.roomApiDomainName" .) | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "workadventure.fullname" . }}-room-api
                port:
                  number: {{ .Values.play.roomApiService.port }}
{{- end }}
