name: Cleanup images and environments

on:
  pull_request:
    types: [closed]

# Enables BuildKit
env:
  DOCKER_BUILDKIT: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  delete_namespace:
    runs-on: ubuntu-latest

    steps:
      # Create a slugified value of the branch
      - uses: rlespinasse/github-slug-action@3.1.0

      - name: Cleanup
        continue-on-error: true
        uses: thecodingmachine/deeployer-cleanup-action@master
        env:
          KUBE_CONFIG_FILE: ${{ secrets.KUBE_CONFIG_FILE }}
        with:
          namespace: workadventure-${{ env.GITHUB_HEAD_REF_SLUG }}
